// Code generated by MockGen. DO NOT EDIT.
// Source: shortener.go
//
// Generated by this command:
//
//	mockgen -source=shortener.go -destination=./mocks/shortener.go -package=handlersmock
//
// Package handlersmock is a generated GoMock package.
package handlersmock

import (
	context "context"
	reflect "reflect"

	"github.com/TPizik/url-shortener/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

type MockshortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockshortenerServiceMockRecorder
}

type MockshortenerServiceMockRecorder struct {
	mock *MockshortenerService
}

func NewMockshortenerService(ctrl *gomock.Controller) *MockshortenerService {
	mock := &MockshortenerService{ctrl: ctrl}
	mock.recorder = &MockshortenerServiceMockRecorder{mock}
	return mock
}

func (m *MockshortenerService) EXPECT() *MockshortenerServiceMockRecorder {
	return m.recorder
}

func (m *MockshortenerService) DeleteURLs(ctx context.Context, urls []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLs", ctx, urls, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockshortenerServiceMockRecorder) DeleteURLs(ctx, urls, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLs", reflect.TypeOf((*MockshortenerService)(nil).DeleteURLs), ctx, urls, userID)
}

func (m *MockshortenerService) GetByShortURL(ctx context.Context, url string) (*domain.ShortenedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShortURL", ctx, url)
	ret0, _ := ret[0].(*domain.ShortenedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockshortenerServiceMockRecorder) GetByShortURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShortURL", reflect.TypeOf((*MockshortenerService)(nil).GetByShortURL), ctx, url)
}

func (m *MockshortenerService) GetInternalStats(ctx context.Context) (*domain.InternalStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternalStats", ctx)
	ret0, _ := ret[0].(*domain.InternalStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockshortenerServiceMockRecorder) GetInternalStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternalStats", reflect.TypeOf((*MockshortenerService)(nil).GetInternalStats), ctx)
}

func (m *MockshortenerService) GetUserURLs(ctx context.Context, userID string) ([]domain.ShortenedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userID)
	ret0, _ := ret[0].([]domain.ShortenedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockshortenerServiceMockRecorder) GetUserURLs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockshortenerService)(nil).GetUserURLs), ctx, userID)
}

func (m *MockshortenerService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockshortenerServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockshortenerService)(nil).Ping), ctx)
}

func (m *MockshortenerService) ShortBatchURL(ctx context.Context, urls []domain.ShortBatchURL, userID string) ([]domain.ShortBatchURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortBatchURL", ctx, urls, userID)
	ret0, _ := ret[0].([]domain.ShortBatchURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockshortenerServiceMockRecorder) ShortBatchURL(ctx, urls, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortBatchURL", reflect.TypeOf((*MockshortenerService)(nil).ShortBatchURL), ctx, urls, userID)
}

func (m *MockshortenerService) ShortURL(ctx context.Context, url, userID string) (*domain.ShortenedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortURL", ctx, url, userID)
	ret0, _ := ret[0].(*domain.ShortenedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockshortenerServiceMockRecorder) ShortURL(ctx, url, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortURL", reflect.TypeOf((*MockshortenerService)(nil).ShortURL), ctx, url, userID)
}
